MongoDB:
    Uri: "mongodb+srv://admin:admin@cluster0-wk7dj.mongodb.net/test?retryWrites=true&w=majority"
    Hostname: "localhost"
    Username: "user1"
    Password: "mypass"
JWTSecret:
    JWTEncodedKey: mysecret1234
  